name: cache-manager -Create Tag

#on:
#  workflow_dispatch:
#    inputs:
#      ref:
#        description: "The branch to checkout when creating the image."
#        required: true
#        default: "release_pipeline"

on:
  push:
    branches:
      - 'release_pipeline'
      
env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}   
  release-version: 0.0.0

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.MY_TOKEN }}   
          
      - name: Tag the release
        run: |
         git tag -a v${{ env.release-version}} -m "Release cache-manager:: ${{ env.release-version}}"
         git push origin --tags