name: Gingersnap cache-manager - Create tag and Publish


on:
 workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
      repository:
        type: string
        default: ${{ github.repository }}
      tag:
        type: string
        default: latest

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "infinispan-qe-bot"
          git config --global user.email "q*@infinispan.org"

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          
      - name: Tag the release
        run: |
         git tag -a v${{ inputs.tag }} -m "Release cache-manager:: ${{ inputs.tag }}"
         git push origin --tags

  publish:
      needs: tag
      uses: ./.github/workflows/publish-images.yaml
      secrets: inherit
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        tag: ${{ inputs.tag }}